baseurl: "/"
url: "https://zebrajaeger.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

exclude:
    - run.cmd
    - deplay.cmd
    - README.md
    - node_modules/
    - package.json
    - package-lock.json
    - .idea/
    - Gemfile
    - Gemfile.lock
    - build.js
